// src/packages/react/racing-bars.ts
import React from 'react';
import { generateId, race, Race } from '../..';
import { getData } from '../shared';

export class RacingBarsComponent extends React.PureComponent {
  public elementId: string;
  public racer: Race | undefined;
  public constructor(props: any) {
    super(props);
    this.elementId = props.elementId || generateId();
  }

  public render() {
    return React.createElement('div', { id: this.elementId });
  }

  public componentDidMount() {
    setTimeout(() => {
      this.runRace();
    });
  }

  public componentDidUpdate() {
    setTimeout(() => {
      this.runRace();
    });
  }

  public componentWillUnmount() {
    this.cleanUp();
  }

  public async runRace() {
    this.cleanUp();
    const { dataPromise, options } = getData(this.props as any, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
  }

  public cleanUp() {
    if (this.racer) {
      this.racer.stop();
    }
  }
}

// src/packages/angular/projects/racing-bars/src/lib/racing-bars.component.ts
import { Component, OnInit } from '@angular/core';
import { generateId, loadData, race, Data } from '../../../../../../dist';
import { getData } from '../../../../../get-data';

@Component({
  selector: 'racing-bars',
  template: `<div id="{{ elementId }}"></div>`,
  styles: [],
})
export class RacingBarsComponent implements OnInit {
  public elementId = generateId();
  public racer: any;

  public ngOnInit(): void {
    loadData('assets/data/population.csv', 'csv').then((data) => {
      race(data as Data[], { selector: '#' + this.elementId });
    });
  }

  async runRace() {
    this.cleanUp();
    const { dataPromise, options } = getData(this.props, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
  }

  cleanUp() {
    if (this.racer) {
      this.racer.stop();
    }
  }
}
