// src/angular/projects/racing-bars/src/lib/racing-bars.component.ts
import {
  Component,
  OnChanges,
  OnInit,
  AfterViewInit,
  OnDestroy,
  ChangeDetectorRef,
  SimpleChanges,
} from '@angular/core';
import { race, Race, Options, generateId } from '../srclib';
import { processProps, Props } from './shared';
import { ComponentProps } from './component-props';

@Component({
  selector: 'racing-bars',
  template: `<div id="{{ elementId }}">{{ loadingContent }}</div>`,
  styles: [
    `
      :host {
        display: block;
      }
      div {
        height: 100%;
        width: 100%;
      }
    `,
  ],
})
export class RacingBarsComponent extends ComponentProps
  implements OnChanges, OnInit, AfterViewInit, OnDestroy {
  public racer: Race;
  private props: Partial<Props>;

  public constructor(private changeDetectorRef: ChangeDetectorRef) {
    super();
  }

  public ngOnChanges(changes: SimpleChanges) {
    this.props = {};
    for (const propName of Object.keys(changes)) {
      this.props[propName] = changes[propName].currentValue;
    }
    if (this.racer) {
      this.racer.changeOptions(this.props as Options);
    }
  }

  public ngOnInit() {
    this.elementId = this.elementId || generateId();
    this.loadingContent = this.loadingContent ?? 'Loading...';
    this.runRace();
  }

  public ngAfterViewInit() {
    this.changeDetectorRef.detach();
  }

  public ngOnDestroy() {
    this.cleanUp();
  }

  private async runRace() {
    this.cleanUp();
    const { dataPromise, options, callback } = processProps(this.props, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
    callback(this.racer, data);
  }

  private cleanUp() {
    if (this.racer) {
      this.racer.destroy();
    }
  }
}

// src/react/racing-bars.ts
// eslint-disable-next-line import/no-extraneous-dependencies
import React from 'react';
import { race, generateId, Race } from '..';
import { processProps, Props } from '../shared';

class RacingBarsComponent extends React.Component {
  public elementId: string;
  public loadingContent: string;
  public racer: Race | undefined;

  public constructor(props: Props) {
    super(props);
    this.elementId = props.elementId || generateId();
    this.loadingContent = props.loadingContent ?? 'Loading...';
  }

  public render() {
    return React.createElement('div', { id: this.elementId }, this.loadingContent);
  }

  public componentDidMount() {
    setTimeout(() => {
      this.runRace();
    });
  }

  public shouldComponentUpdate(nextProps: Props) {
    if (this.racer) {
      // TODO: do not download data
      const { options } = processProps(nextProps, this.elementId);
      this.racer.changeOptions(options);
    }
    return false;
  }

  public componentWillUnmount() {
    this.cleanUp();
  }

  private async runRace() {
    this.cleanUp();
    const { dataPromise, options, callback } = processProps(this.props as Props, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
    callback(this.racer, data);
  }

  private cleanUp() {
    if (this.racer) {
      this.racer.destroy();
    }
  }
}

export default RacingBarsComponent;
