// src/packages/angular/projects/racing-bars/src/lib/racing-bars.component.ts
import { Component, OnInit } from '@angular/core';
import { generateId, loadData, race, Data } from '../../../../../../dist';
import { getData } from '../../../../../get-data';

@Component({
  selector: 'racing-bars',
  template: `<div id="{{ elementId }}"></div>`,
  styles: [],
})
export class RacingBarsComponent implements OnInit {
  public elementId = generateId();
  public racer: any;

  public ngOnInit(): void {
    loadData('assets/data/population.csv', 'csv').then((data) => {
      race(data as Data[], { selector: '#' + this.elementId });
    });
  }

  async runRace() {
    this.cleanUp();
    const { dataPromise, options } = getData(this.props, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
  }

  cleanUp() {
    if (this.racer) {
      this.racer.stop();
    }
  }
}

// packages/react/racing-bars.js
/* eslint-disable */
import React from 'react';
import { generateId, race } from '../../dist/racing-bars.esm';
import { getData } from '../get-data';

export class RacingBarsComponent extends React.Component {
  constructor(props) {
    super(props);
    this.props = props;
    this.elementId = generateId();
  }

  render() {
    return React.createElement('div', { id: this.elementId });
  }

  componentDidMount() {
    setTimeout(() => {
      this.runRace();
    });
  }

  componentDidUpdate() {
    setTimeout(() => {
      this.runRace();
    });
  }

  componentWillUnmount() {
    this.cleanUp();
  }

  async runRace() {
    this.cleanUp();
    const { dataPromise, options } = getData(this.props, this.elementId);
    const data = await dataPromise;
    this.racer = race(data, options);
  }

  cleanUp() {
    if (this.racer) {
      this.racer.stop();
    }
  }
}
